export const LOAD_CART = 'LOAD_CART';
export const INCREMENT_OR_DECREMENT_PRODUCT = 'INCREMENT_OR_DECREMENT_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_CART = 'UPDATE_CART';
